### ISSUE TITLE
integrating with flask blog

### ISSUE THREAD

**Issue by TheHackitect** [Quarcoo-arc/interactive-coments-section#1]
Hello
I must commend you on this awesome project! its really top-notch.

Please I will need to integrate this with by websites for comments on posts. how do i go about this? I have a website running on a flask server. admins / authors can create post. please how do I integrate this for post comments?

**Comment by Quarcoo-arc** [comment]
Thanks for the commendation.

You could probably include a link to this project hosted on a different server on your website, so that once someone wants to comment, it takes the person to a different webpage. But you'd have to structure your database such that its able to determine which post the user is commenting on.

**Comment by TheHackitect** [comment]
alright. thanks so much for the help.  I am really grateful
